### ISSUE TITLE
Can the dataset include values greater than 1?

### ISSUE THREAD

**Issue by sunilsp77** [Spyna/react-svg-radar-chart#16]
Example: values for the keys are greater than 1. Is this possible, because it was not working for me?    
const data = [
      {
        data: {
          0: 45,
          1: 67,
          2: 95,
          3: 27,
          4: 24,
          5: 20,
          6: 40
        },
        meta: { color: "blue" }
      }
    ];

**Comment by Spyna** [comment]
Hi, 
no it can't numbers must be in 0-1 range. 
you should contrain the values in that range.
