### ISSUE TITLE
mouseEnter for shapes?

### ISSUE THREAD

**Issue by adelghaenian** [Spyna/react-svg-radar-chart#18]
How can we show a tooltip by pointing at shapes?

**Comment by Spyna** [comment]
Hi, 
this is not possible, and I would say is not in the scope of this library.

However, you can add an event listener on the shapes, using the class `shape` or whatever class you give to the shapes. Be sure to add the listener when the shapes are rendered on the page, so typically in the `componentDidMount` function of the react component.

```
 componentDidMount() {

    function onMouseOver(event) {
      console.log(event)
      //display the tooltip
    }
    document.querySelectorAll(".shape").forEach(element => element.addEventListener("mouseover", onMouseOver))
  }
```

Or you can handle `mouseEnter` and `mouseLeave` events on the dots: 

```JS
 options: {
      dots: true,
      dotProps: (meta) => ({
        className: "dot",
        mouseEnter: function(point) { console.log("MouseEnter", point)},
        mouseLeave: function() { console.log("MouseLeave")},
      }),
    },
```
