### ISSUE TITLE
The package seems to be broken

### ISSUE THREAD

**Issue by WhyThat** [Spyna/react-svg-radar-chart#7]
Hey,
Thanks to have update the package yesterday, but I think something wrong happened when you bumped the package.

I will open a new PR with some improvements in the build process. 

![](https://goo.gl/5xf6FK)
The `build` folder is missing.

**Comment by WhyThat** [comment]
Hey,
I think you forgot to re-publish the new package ^^
Best regards !

**Comment by Spyna** [comment]
ups, published

**Comment by WhyThat** [comment]
Hello,
Thanks for the update, but the css file is missing,
It isn't copied during the build ?
